@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Mar 03 09:34:18 +0330 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto e02fcbbf2ee5494f9d4af67fa6f5d342 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot varify_main_behav xil_defaultlib.varify_main -log elaborate.log"
call xelab  -wto e02fcbbf2ee5494f9d4af67fa6f5d342 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot varify_main_behav xil_defaultlib.varify_main -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
